### PR TITLE
Change the default behavior to take arguments, and filter them by what's opted in

### PR DESCRIPTION
**Pull request by dfithian**
I changed a line in `app/simformat.hs` and then ran these:

* `simformat src` -> no change
* `simformat app` -> reformatted
* `simformat` -> reformatted

### CODE REVIEW

**Comment by dfithian** [comment]
Hm if I run this on the command line it works as expected but if I run it in Code then it formats a file not in

**Comment by bergey** [comment]
What's the search path for `.simlintrc`?  Does it search up from the starting directory, or assume it's called from the repo root?  I've seen editors frequently exec from the directory that holds the file.

**Comment by dfithian** [comment]
Good call, it was calling from somewhere else!

**Comment by dfithian** [comment]
Alright I added some tests. @bergey let me know if you want to try this out on your editor setup before I merge?

**Review by bergey — APPROVED** [review]
LGTM.  No change to the `Editor` mode, so I don't imagine my setup is affected.

**Pull request merged**
